# Generated by Django 6.0.2 on 2026-04-08 14:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Seccao',
            fields=[
                ('nome', models.CharField(max_length=512, primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'seccao',
            },
        ),
        migrations.CreateModel(
            name='Venda',
            fields=[
                ('recibo', models.BigIntegerField(primary_key=True, serialize=False)),
                ('total', models.BigIntegerField()),
                ('data', models.DateField()),
            ],
            options={
                'db_table': 'venda',
            },
        ),
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=512)),
                ('preco', models.IntegerField()),
                ('qtd', models.IntegerField()),
                ('desconto', models.IntegerField()),
                ('iva', models.IntegerField()),
                ('seccao', models.ForeignKey(db_column='seccao_nome', on_delete=django.db.models.deletion.RESTRICT, related_name='produtos', to='workshop.seccao')),
            ],
            options={
                'db_table': 'produto',
            },
        ),
        migrations.CreateModel(
            name='VendeSe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qtd', models.IntegerField()),
                ('preco', models.IntegerField()),
                ('produto', models.ForeignKey(db_column='produto_id', on_delete=django.db.models.deletion.RESTRICT, related_name='linhas_venda', to='workshop.produto')),
                ('venda', models.ForeignKey(db_column='venda_recibo', on_delete=django.db.models.deletion.RESTRICT, related_name='linhas', to='workshop.venda')),
            ],
            options={
                'db_table': 'vende_se',
                'unique_together': {('venda', 'produto')},
            },
        ),
    ]
