# Generated by Django 6.0.2 on 2026-04-08 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workshop', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produto',
            name='preco',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='vendese',
            name='preco',
            field=models.FloatField(),
        ),
    ]
