# Generated by Django 6.0.2 on 2026-04-12 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workshop', '0002_alter_produto_preco_alter_vendese_preco'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venda',
            name='total',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
