# Generated by Django 6.0.2 on 2026-05-12 12:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workshop', '0004_alter_venda_data'),
    ]

    operations = [
        migrations.CreateModel(
            name='Loja',
            fields=[
                ('nomeloja', models.CharField(max_length=512, primary_key=True, serialize=False)),
                ('localizacao', models.CharField(max_length=512)),
                ('capitalsocial', models.IntegerField()),
                ('emailloja', models.CharField(max_length=512)),
                ('contacto', models.IntegerField()),
            ],
            options={
                'db_table': 'loja',
            },
        ),
        migrations.CreateModel(
            name='Owner',
            fields=[
                ('cc', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=512)),
                ('birth', models.DateField()),
                ('email', models.CharField(max_length=512)),
                ('contact', models.IntegerField()),
                ('morada', models.BooleanField()),
            ],
            options={
                'db_table': 'owner',
            },
        ),
        migrations.AlterField(
            model_name='produto',
            name='preco',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='venda',
            name='data',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='venda',
            name='total',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='vendese',
            name='preco',
            field=models.IntegerField(),
        ),
        migrations.AddField(
            model_name='seccao',
            name='loja',
            field=models.ForeignKey(db_column='loja_nomeloja', null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='seccoes', to='workshop.loja'),
        ),
        migrations.AddField(
            model_name='loja',
            name='owner',
            field=models.ForeignKey(db_column='owner_cc', on_delete=django.db.models.deletion.RESTRICT, related_name='lojas', to='workshop.owner'),
        ),
    ]
