# Generated by Django 6.0.2 on 2026-05-18 17:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workshop', '0005_loja_owner_alter_produto_preco_alter_venda_data_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='loja',
            field=models.ForeignKey(db_column='loja_nomeloja', null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='produtos', to='workshop.loja'),
        ),
    ]
