# Generated by Django 6.0.2 on 2026-05-25 22:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workshop', '0006_produto_loja'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fornecedor',
            fields=[
                ('nif', models.IntegerField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=512)),
                ('email', models.CharField(max_length=512)),
                ('contacto', models.IntegerField()),
                ('morada', models.CharField(max_length=512)),
            ],
            options={
                'db_table': 'fornecedor',
            },
        ),
        migrations.AddField(
            model_name='produto',
            name='fornecedor',
            field=models.ForeignKey(db_column='fornecedor_nif', null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='produtos', to='workshop.fornecedor'),
        ),
    ]
