# Generated by Django 6.0.2 on 2026-06-09 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workshop', '0009_alter_produto_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='oculto',
            field=models.BooleanField(default=False),
        ),
    ]
