# Generated by Django 6.0.2 on 2026-06-11 13:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workshop', '0010_produto_oculto'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contacto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=512)),
                ('telefone', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'contacto',
            },
        ),
        migrations.AddField(
            model_name='venda',
            name='metodo_pagamento',
            field=models.CharField(choices=[('dinheiro', 'Dinheiro'), ('mbway', 'MBWay')], default='dinheiro', max_length=20),
        ),
        migrations.AddField(
            model_name='venda',
            name='contacto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vendas', to='workshop.contacto'),
        ),
    ]
