# Generated by Django 6.0.2 on 2026-06-12 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workshop', '0011_contacto_venda_metodo_pagamento_venda_contacto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venda',
            name='data',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='venda',
            name='total',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='vendese',
            name='preco',
            field=models.FloatField(),
        ),
    ]
