# Generated by Django 6.0.2 on 2026-06-18 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workshop', '0012_alter_venda_data_alter_venda_total_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='loja',
            name='oculta',
            field=models.BooleanField(default=False),
        ),
    ]
