# Generated by Django 6.0.2 on 2026-06-18 10:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workshop', '0014_evento'),
    ]

    operations = [
        migrations.AddField(
            model_name='venda',
            name='evento',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vendas', to='workshop.evento'),
        ),
    ]
